//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulmaBullaFastFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public int customerId { get; set; }
        public string food { get; set; }
        public string drink { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public decimal price { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
